# config.properties

# Configurações SMTP
email.smtp.host=smtp.gmail.com
email.smtp.port=587
email.smtp.auth=true
email.smtp.starttls.enable=true

# Credenciais
email.remetente=contato.vladcorp@gmail.com
email.senha=qysa ixms uidx oqbi

# Configurações opcionais
email.smtp.connectiontimeout=5000
email.smtp.timeout=5000
email.debug=false